<?php
/**
 * AccountsTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Obada
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OBADA API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Obada\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AccountsTest Class Doc Comment
 *
 * @category    Class
 * @description Accounts
 * @package     Obada
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AccountsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Accounts"
     */
    public function testAccounts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hdAccounts"
     */
    public function testPropertyHdAccounts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "importedAccounts"
     */
    public function testPropertyImportedAccounts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
