<?php
/**
 * DefaultApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Obada
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * client-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Obada\Test\Api;

use \Obada\Configuration;
use \Obada\ApiException;
use \Obada\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Obada
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for aa7a8417Bb9b4897B4dc03b0f56e852a
     *
     * Get Client Obit.
     *
     */
    public function testAa7a8417Bb9b4897B4dc03b0f56e852a()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for b5523ce75ca3402cBea94616caf10295
     *
     * Save Client Obit.
     *
     */
    public function testB5523ce75ca3402cBea94616caf10295()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for call3ff98b15F7624dadBf5c165e2131e950
     *
     * Upload Obit to Blockchain.
     *
     */
    public function testCall3ff98b15F7624dadBf5c165e2131e950()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for call582a6705Ad704a638373A2da8d44a3cf
     *
     * Download Obit from Blockchain.
     *
     */
    public function testCall582a6705Ad704a638373A2da8d44a3cf()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for call6e9d1c55D0f34caaBe6dB479f34401ce
     *
     * Generate Obit.
     *
     */
    public function testCall6e9d1c55D0f34caaBe6dB479f34401ce()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for call915b874a1e4945909805F077e19f99ca
     *
     * Get Obit From Blockchain.
     *
     */
    public function testCall915b874a1e4945909805F077e19f99ca()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
