<?php
/**
 * NFTApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Obada
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OBADA API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Obada\Test\Api;

use \Obada\Configuration;
use \Obada\ApiException;
use \Obada\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * NFTApiTest Class Doc Comment
 *
 * @category Class
 * @package  Obada
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NFTApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for batchMint
     *
     * Mints batches of NFT.
     *
     */
    public function testBatchMint()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for batchSend
     *
     * Send a batch of NFTs to another address.
     *
     */
    public function testBatchSend()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mint
     *
     * Mints NFT.
     *
     */
    public function testMint()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for nft
     *
     * Fetch NFT from OBADA blockchain Node.
     *
     */
    public function testNft()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for send
     *
     * Send NFT to another address.
     *
     */
    public function testSend()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateMetadata
     *
     * Update NFT metadata.
     *
     */
    public function testUpdateMetadata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
